### ISSUE TITLE
Missing files for training on CIFAR

### ISSUE THREAD

**Issue by mshahbazi72** [PeterouZh/Omni-GAN-PyTorch#4]
Hi
I am trying to run the provided code on CIFAR as instructed in the Readme file. However, there are some errors when trying to import some modules. It seems they are missing from the code folder
Is the full code for CIFAR experiments also not available yet, and is going to be released later with the ImageNet code?

**Comment by PeterouZh** [comment]
The current code for the CIFAR experiments should be runnable.  Could you post your error message?

**Comment by mshahbazi72** [comment]
When I use the command to run train.py from exp/omni_loss, it cannot import inception_utils, utils, losses, and template_lib.v2
I guess they exist in the repo, but just not in the right directory

**Comment by PeterouZh** [comment]
You should run train.py at the project root dir.  
Try 
```bash
export PYTHONPATH=./exp:./:./BigGAN_PyTorch_1_lib
python exp/omni_loss/train.py ...

```
