### ISSUE TITLE
Can you share your trained Omni-GAN models on ImageNet about both 128 and 256 resolution?

### ISSUE THREAD

**Issue by BenfenYU** [PeterouZh/Omni-GAN-PyTorch#5]
Excellent job! Can you share your trained Omni-GAN models on ImageNet about both 128 and 256 resolution?
Thanks!

**Comment by PeterouZh** [comment]
Sorry to reply late. The models are currently saved inside the company, and it is almost impossible to be allowed to release. Maybe I will reproduce some models outside the company.
